# === MAIN ===
resolution = 1024
iteration_limit_power = 9
escape_threshold = 2.0
density_range = [16, 16]
render_plane = [-1.75, -1.25, 0.75, 1.25]
# workers = -1

# == FLAGS ===

# NOTE: These will auto-disable if rendering multiple frames
save_histogram_png = true
progress_indicator = true
save_render_data = true

# IMPORTANT: Set true if there's no contiguous non-escaping regions
skip_hist_boundary_check = false

# Generally leave this alone unless you're having issues
skip_hist_optimization = false
